; tpost0.g
; called after tool 0 has been selected
;
; generated by RepRapFirmware Configuration Tool v3.4.0-LPC-STM32+4 on Tue Aug 23 2022 13:05:37 GMT+0200 (CEST)
; Wait for set temperatures to be reached
M116 P0

