; retractprobe.g
; called to retract a physical Z probe
;
; generated by RepRapFirmware Configuration Tool v3.4.0-LPC-STM32+4 on Tue Aug 23 2022 13:05:35 GMT+0200 (CEST)
M280 P0 S90 ; retract BLTouch
