; stop.g
; called when M0 (Stop) is run (e.g. when a print from SD card is cancelled)
;
; generated by RepRapFirmware Configuration Tool v3.4.0-LPC-STM32+2 on Wed Jun 15 2022 09:35:16 GMT+0200 (Mitteleuropäische Sommerzeit)

